config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :itinerario_metros
  resources :itinerarios
  resources :estacaos
  resources :estacao_metros
  resources :metros
  resources :linha_metros
  resources :empresas
  resources :condutors
  resources :cobradors
  resources :onibuses
  resources :linha_cartaos
  resources :cartaos
  resources :cidades
  resources :linhas
  resources :usuarios

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cartao.rb
class Cartao < ApplicationRecord
  belongs_to :usuario
end

app/models/cidade.rb
class Cidade < ApplicationRecord
end

app/models/cobrador.rb
class Cobrador < ApplicationRecord
  belongs_to :onibus
  belongs_to :empresa
end

app/models/condutor.rb
class Condutor < ApplicationRecord
  belongs_to :onibus
  belongs_to :empresa
end

app/models/empresa.rb
class Empresa < ApplicationRecord
end

app/models/estacao.rb
class Estacao < ApplicationRecord
  belongs_to :cidade
end

app/models/estacao_metro.rb
class EstacaoMetro < ApplicationRecord
  belongs_to :cidade
end

app/models/itinerario.rb
class Itinerario < ApplicationRecord
  belongs_to :estacao
  belongs_to :linha
end

app/models/linha.rb
class Linha < ApplicationRecord
end

app/models/linha_cartao.rb
class LinhaCartao < ApplicationRecord
  belongs_to :cartao
  belongs_to :linha
end

app/models/linha_metro.rb
class LinhaMetro < ApplicationRecord
end

app/models/metro.rb
class Metro < ApplicationRecord
  belongs_to :linha_metro
  belongs_to :empresa
end

app/models/onibus.rb
class Onibus < ApplicationRecord
  belongs_to :empresa
  belongs_to :linha
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/linha_metros_controller.rb
class LinhaMetrosController < ApplicationController
  before_action :set_linha_metro, only: [:show, :edit, :update, :destroy]

  # GET /linha_metros
  # GET /linha_metros.json
  def index
    @linha_metros = LinhaMetro.all
  end

  # GET /linha_metros/1
  # GET /linha_metros/1.json
  def show
  end

  # GET /linha_metros/new
  def new
    @linha_metro = LinhaMetro.new
  end

  # GET /linha_metros/1/edit
  def edit
  end

  # POST /linha_metros
  # POST /linha_metros.json
  def create
    @linha_metro = LinhaMetro.new(linha_metro_params)

    respond_to do |format|
      if @linha_metro.save
        format.html { redirect_to @linha_metro, notice: 'Linha metro was successfully created.' }
        format.json { render :show, status: :created, location: @linha_metro }
      else
        format.html { render :new }
        format.json { render json: @linha_metro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /linha_metros/1
  # PATCH/PUT /linha_metros/1.json
  def update
    respond_to do |format|
      if @linha_metro.update(linha_metro_params)
        format.html { redirect_to @linha_metro, notice: 'Linha metro was successfully updated.' }
        format.json { render :show, status: :ok, location: @linha_metro }
      else
        format.html { render :edit }
        format.json { render json: @linha_metro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /linha_metros/1
  # DELETE /linha_metros/1.json
  def destroy
    @linha_metro.destroy
    respond_to do |format|
      format.html { redirect_to linha_metros_url, notice: 'Linha metro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_linha_metro
      @linha_metro = LinhaMetro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def linha_metro_params
      params.require(:linha_metro).permit(:numero_paradas, :cor, :passageiros_atendidos, :qtd_trans)
    end
end

app/helpers/cartaos_helper.rb
module CartaosHelper
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/estacaos_helper.rb
module EstacaosHelper
end

app/helpers/linha_metros_helper.rb
module LinhaMetrosHelper
end

app/helpers/linhas_helper.rb
module LinhasHelper
end

app/helpers/metros_helper.rb
module MetrosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/linha_metros/_form.html.erb
<%= form_with(model: linha_metro, local: true) do |form| %>
  <% if linha_metro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(linha_metro.errors.count, "error") %> prohibited this linha_metro from being saved:</h2>

      <ul>
      <% linha_metro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :numero_paradas %>
    <%= form.number_field :numero_paradas, id: :linha_metro_numero_paradas %>
  </div>

  <div class="field">
    <%= form.label :cor %>
    <%= form.text_field :cor, id: :linha_metro_cor %>
  </div>

  <div class="field">
    <%= form.label :passageiros_atendidos %>
    <%= form.text_field :passageiros_atendidos, id: :linha_metro_passageiros_atendidos %>
  </div>

  <div class="field">
    <%= form.label :qtd_trans %>
    <%= form.text_field :qtd_trans, id: :linha_metro_qtd_trans %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/linha_metros/edit.html.erb
<h1>Editing Linha Metro</h1>

<%= render 'form', linha_metro: @linha_metro %>

<%= link_to 'Show', @linha_metro %> |
<%= link_to 'Back', linha_metros_path %>

app/views/linha_metros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Linha_Metrôs</h1>

<table>
  <thead>
    <tr>
      <th>Numero paradas</th>
      <th>Cor</th>
      <th>Passageiros atendidos</th>
      <th>Qtd trans</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @linha_metros.each do |linha_metro| %>
      <tr>
        <td><%= linha_metro.numero_paradas %></td>
        <td><%= linha_metro.cor %></td>
        <td><%= linha_metro.passageiros_atendidos %></td>
        <td><%= linha_metro.qtd_trans %></td>
        <td><%= link_to 'Show', linha_metro %></td>
        <td><%= link_to 'Edit', edit_linha_metro_path(linha_metro) %></td>
        <td><%= link_to 'Destroy', linha_metro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Linha Metro', new_linha_metro_path %>
<%= link_to 'Back', welcome_index_path %>

app/views/linha_metros/new.html.erb
<h1>New Linha Metro</h1>

<%= render 'form', linha_metro: @linha_metro %>

<%= link_to 'Back', linha_metros_path %>

app/views/linha_metros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Numero paradas:</strong>
  <%= @linha_metro.numero_paradas %>
</p>

<p>
  <strong>Cor:</strong>
  <%= @linha_metro.cor %>
</p>

<p>
  <strong>Passageiros atendidos:</strong>
  <%= @linha_metro.passageiros_atendidos %>
</p>

<p>
  <strong>Qtd trans:</strong>
  <%= @linha_metro.qtd_trans %>
</p>

<%= link_to 'Edit', edit_linha_metro_path(@linha_metro) %> |
<%= link_to 'Back', linha_metros_path %>