config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :itinerario_metros
  resources :itinerarios
  resources :estacaos
  resources :estacao_metros
  resources :metros
  resources :linha_metros
  resources :empresas
  resources :condutors
  resources :cobradors
  resources :onibuses
  resources :linha_cartaos
  resources :cartaos
  resources :cidades
  resources :linhas
  resources :usuarios

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cartao.rb
class Cartao < ApplicationRecord
  belongs_to :usuario
end

app/models/cidade.rb
class Cidade < ApplicationRecord
end

app/models/cobrador.rb
class Cobrador < ApplicationRecord
  belongs_to :onibus
  belongs_to :empresa
end

app/models/condutor.rb
class Condutor < ApplicationRecord
  belongs_to :onibus
  belongs_to :empresa
end

app/models/empresa.rb
class Empresa < ApplicationRecord
end

app/models/estacao.rb
class Estacao < ApplicationRecord
  belongs_to :cidade
end

app/models/estacao_metro.rb
class EstacaoMetro < ApplicationRecord
  belongs_to :cidade
end

app/models/itinerario.rb
class Itinerario < ApplicationRecord
  belongs_to :estacao
  belongs_to :linha
end

app/models/itinerario_metro.rb
class ItinerarioMetro < ApplicationRecord
  belongs_to :estacao_metro
  belongs_to :linha_metro
end

app/models/linha.rb
class Linha < ApplicationRecord
end

app/models/linha_cartao.rb
class LinhaCartao < ApplicationRecord
  belongs_to :cartao
  belongs_to :linha
end

app/models/linha_metro.rb
class LinhaMetro < ApplicationRecord
end

app/models/metro.rb
class Metro < ApplicationRecord
  belongs_to :linha_metro
  belongs_to :empresa
end

app/models/onibus.rb
class Onibus < ApplicationRecord
  belongs_to :empresa
  belongs_to :linha
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/itinerario_metros_controller.rb
class ItinerarioMetrosController < ApplicationController
  before_action :set_itinerario_metro, only: [:show, :edit, :update, :destroy]

  # GET /itinerario_metros
  # GET /itinerario_metros.json
  def index
    @itinerario_metros = ItinerarioMetro.all
  end

  # GET /itinerario_metros/1
  # GET /itinerario_metros/1.json
  def show
  end

  # GET /itinerario_metros/new
  def new
    @itinerario_metro = ItinerarioMetro.new
  end

  # GET /itinerario_metros/1/edit
  def edit
  end

  # POST /itinerario_metros
  # POST /itinerario_metros.json
  def create
    @itinerario_metro = ItinerarioMetro.new(itinerario_metro_params)

    respond_to do |format|
      if @itinerario_metro.save
        format.html { redirect_to @itinerario_metro, notice: 'Itinerario metro was successfully created.' }
        format.json { render :show, status: :created, location: @itinerario_metro }
      else
        format.html { render :new }
        format.json { render json: @itinerario_metro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /itinerario_metros/1
  # PATCH/PUT /itinerario_metros/1.json
  def update
    respond_to do |format|
      if @itinerario_metro.update(itinerario_metro_params)
        format.html { redirect_to @itinerario_metro, notice: 'Itinerario metro was successfully updated.' }
        format.json { render :show, status: :ok, location: @itinerario_metro }
      else
        format.html { render :edit }
        format.json { render json: @itinerario_metro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /itinerario_metros/1
  # DELETE /itinerario_metros/1.json
  def destroy
    @itinerario_metro.destroy
    respond_to do |format|
      format.html { redirect_to itinerario_metros_url, notice: 'Itinerario metro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_itinerario_metro
      @itinerario_metro = ItinerarioMetro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def itinerario_metro_params
      params.require(:itinerario_metro).permit(:estacao_metro_id, :linha_metro_id, :ordem)
    end
end

app/helpers/cartaos_helper.rb
module CartaosHelper
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/itinerario_metros_helper.rb
module ItinerarioMetrosHelper
end

app/helpers/linhas_helper.rb
module LinhasHelper
end

app/helpers/metros_helper.rb
module MetrosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/itinerario_metros/_form.html.erb
<%= form_with(model: itinerario_metro, local: true) do |form| %>
  <% if itinerario_metro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(itinerario_metro.errors.count, "error") %> prohibited this itinerario_metro from being saved:</h2>

      <ul>
      <% itinerario_metro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :estacao_metro_id %>
    <%= form.text_field :estacao_metro_id, id: :itinerario_metro_estacao_metro_id %>
  </div>

  <div class="field">
    <%= form.label :linha_metro_id %>
    <%= form.text_field :linha_metro_id, id: :itinerario_metro_linha_metro_id %>
  </div>

  <div class="field">
    <%= form.label :ordem %>
    <%= form.number_field :ordem, id: :itinerario_metro_ordem %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/itinerario_metros/edit.html.erb
<h1>Editing Itinerario Metro</h1>

<%= render 'form', itinerario_metro: @itinerario_metro %>

<%= link_to 'Show', @itinerario_metro %> |
<%= link_to 'Back', itinerario_metros_path %>

app/views/itinerario_metros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Itinerário_Metrôs</h1>

<table>
  <thead>
    <tr>
      <th>Estacao metro</th>
      <th>Linha metro</th>
      <th>Ordem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @itinerario_metros.each do |itinerario_metro| %>
      <tr>
        <td><%= itinerario_metro.estacao_metro %></td>
        <td><%= itinerario_metro.linha_metro %></td>
        <td><%= itinerario_metro.ordem %></td>
        <td><%= link_to 'Show', itinerario_metro %></td>
        <td><%= link_to 'Edit', edit_itinerario_metro_path(itinerario_metro) %></td>
        <td><%= link_to 'Destroy', itinerario_metro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Itinerario Metro', new_itinerario_metro_path %>
<%= link_to 'Back', welcome_index_path %>

app/views/itinerario_metros/new.html.erb
<h1>New Itinerario Metro</h1>

<%= render 'form', itinerario_metro: @itinerario_metro %>

<%= link_to 'Back', itinerario_metros_path %>

app/views/itinerario_metros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Estacao metro:</strong>
  <%= @itinerario_metro.estacao_metro %>
</p>

<p>
  <strong>Linha metro:</strong>
  <%= @itinerario_metro.linha_metro %>
</p>

<p>
  <strong>Ordem:</strong>
  <%= @itinerario_metro.ordem %>
</p>

<%= link_to 'Edit', edit_itinerario_metro_path(@itinerario_metro) %> |
<%= link_to 'Back', itinerario_metros_path %>