config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :itinerario_metros
  resources :itinerarios
  resources :estacaos
  resources :estacao_metros
  resources :metros
  resources :linha_metros
  resources :empresas
  resources :condutors
  resources :cobradors
  resources :onibuses
  resources :linha_cartaos
  resources :cartaos
  resources :cidades
  resources :linhas
  resources :usuarios

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cartao.rb
class Cartao < ApplicationRecord
  belongs_to :usuario
end

app/models/cidade.rb
class Cidade < ApplicationRecord
end

app/models/cobrador.rb
class Cobrador < ApplicationRecord
  belongs_to :onibus
  belongs_to :empresa
end

app/models/condutor.rb
class Condutor < ApplicationRecord
  belongs_to :onibus
  belongs_to :empresa
end

app/models/empresa.rb
class Empresa < ApplicationRecord
end

app/models/estacao.rb
class Estacao < ApplicationRecord
  belongs_to :cidade
end

app/models/estacao_metro.rb
class EstacaoMetro < ApplicationRecord
  belongs_to :cidade
end

app/models/itinerario.rb
class Itinerario < ApplicationRecord
  belongs_to :estacao
  belongs_to :linha
end

app/models/linha.rb
class Linha < ApplicationRecord
end

app/models/linha_cartao.rb
class LinhaCartao < ApplicationRecord
  belongs_to :cartao
  belongs_to :linha
end

app/models/linha_metro.rb
class LinhaMetro < ApplicationRecord
end

app/models/metro.rb
class Metro < ApplicationRecord
  belongs_to :linha_metro
  belongs_to :empresa
end

app/models/onibus.rb
class Onibus < ApplicationRecord
  belongs_to :empresa
  belongs_to :linha
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/linha_cartaos_controller.rb
class LinhaCartaosController < ApplicationController
  before_action :set_linha_cartao, only: [:show, :edit, :update, :destroy]

  # GET /linha_cartaos
  # GET /linha_cartaos.json
  def index
    @linha_cartaos = LinhaCartao.all
  end

  # GET /linha_cartaos/1
  # GET /linha_cartaos/1.json
  def show
  end

  # GET /linha_cartaos/new
  def new
    @linha_cartao = LinhaCartao.new
  end

  # GET /linha_cartaos/1/edit
  def edit
  end

  # POST /linha_cartaos
  # POST /linha_cartaos.json
  def create
    @linha_cartao = LinhaCartao.new(linha_cartao_params)

    respond_to do |format|
      if @linha_cartao.save
        format.html { redirect_to @linha_cartao, notice: 'Linha cartao was successfully created.' }
        format.json { render :show, status: :created, location: @linha_cartao }
      else
        format.html { render :new }
        format.json { render json: @linha_cartao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /linha_cartaos/1
  # PATCH/PUT /linha_cartaos/1.json
  def update
    respond_to do |format|
      if @linha_cartao.update(linha_cartao_params)
        format.html { redirect_to @linha_cartao, notice: 'Linha cartao was successfully updated.' }
        format.json { render :show, status: :ok, location: @linha_cartao }
      else
        format.html { render :edit }
        format.json { render json: @linha_cartao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /linha_cartaos/1
  # DELETE /linha_cartaos/1.json
  def destroy
    @linha_cartao.destroy
    respond_to do |format|
      format.html { redirect_to linha_cartaos_url, notice: 'Linha cartao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_linha_cartao
      @linha_cartao = LinhaCartao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def linha_cartao_params
      params.require(:linha_cartao).permit(:cartao_id, :linha_id)
    end
end

app/helpers/cartaos_helper.rb
module CartaosHelper
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/estacaos_helper.rb
module EstacaosHelper
end

app/helpers/linha_cartaos_helper.rb
module LinhaCartaosHelper
end

app/helpers/linhas_helper.rb
module LinhasHelper
end

app/helpers/metros_helper.rb
module MetrosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/linha_cartaos/_form.html.erb
<%= form_with(model: linha_cartao, local: true) do |form| %>
  <% if linha_cartao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(linha_cartao.errors.count, "error") %> prohibited this linha_cartao from being saved:</h2>

      <ul>
      <% linha_cartao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cartao_id %>
    <%= form.text_field :cartao_id, id: :linha_cartao_cartao_id %>
  </div>

  <div class="field">
    <%= form.label :linha_id %>
    <%= form.text_field :linha_id, id: :linha_cartao_linha_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/linha_cartaos/edit.html.erb
<h1>Editing Linha Cartao</h1>

<%= render 'form', linha_cartao: @linha_cartao %>

<%= link_to 'Show', @linha_cartao %> |
<%= link_to 'Back', linha_cartaos_path %>

app/views/linha_cartaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Linha_Cartões</h1>

<table>
  <thead>
    <tr>
      <th>Cartao</th>
      <th>Linha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @linha_cartaos.each do |linha_cartao| %>
      <tr>
        <td><%= linha_cartao.cartao %></td>
        <td><%= linha_cartao.linha %></td>
        <td><%= link_to 'Show', linha_cartao %></td>
        <td><%= link_to 'Edit', edit_linha_cartao_path(linha_cartao) %></td>
        <td><%= link_to 'Destroy', linha_cartao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Linha Cartao', new_linha_cartao_path %>
<%= link_to 'Back', welcome_index_path %>

app/views/linha_cartaos/new.html.erb
<h1>New Linha Cartao</h1>

<%= render 'form', linha_cartao: @linha_cartao %>

<%= link_to 'Back', linha_cartaos_path %>

app/views/linha_cartaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cartao:</strong>
  <%= @linha_cartao.cartao %>
</p>

<p>
  <strong>Linha:</strong>
  <%= @linha_cartao.linha %>
</p>

<%= link_to 'Edit', edit_linha_cartao_path(@linha_cartao) %> |
<%= link_to 'Back', linha_cartaos_path %>