config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :itinerario_metros
  resources :itinerarios
  resources :estacaos
  resources :estacao_metros
  resources :metros
  resources :linha_metros
  resources :empresas
  resources :condutors
  resources :cobradors
  resources :onibuses
  resources :linha_cartaos
  resources :cartaos
  resources :cidades
  resources :linhas
  resources :usuarios

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cartao.rb
class Cartao < ApplicationRecord
  belongs_to :usuario
end

app/models/cidade.rb
class Cidade < ApplicationRecord
end

app/models/cobrador.rb
class Cobrador < ApplicationRecord
  belongs_to :onibus
  belongs_to :empresa
end

app/models/condutor.rb
class Condutor < ApplicationRecord
  belongs_to :onibus
  belongs_to :empresa
end

app/models/empresa.rb
class Empresa < ApplicationRecord
end

app/models/estacao.rb
class Estacao < ApplicationRecord
  belongs_to :cidade
end

app/models/estacao_metro.rb
class EstacaoMetro < ApplicationRecord
  belongs_to :cidade
end

app/models/itinerario.rb
class Itinerario < ApplicationRecord
  belongs_to :estacao
  belongs_to :linha
end

app/models/linha.rb
class Linha < ApplicationRecord
end

app/models/linha_cartao.rb
class LinhaCartao < ApplicationRecord
  belongs_to :cartao
  belongs_to :linha
end

app/models/linha_metro.rb
class LinhaMetro < ApplicationRecord
end

app/models/metro.rb
class Metro < ApplicationRecord
  belongs_to :linha_metro
  belongs_to :empresa
end

app/models/onibus.rb
class Onibus < ApplicationRecord
  belongs_to :empresa
  belongs_to :linha
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/cidades_controller.rb
class CidadesController < ApplicationController
  before_action :set_cidade, only: [:show, :edit, :update, :destroy]

  # GET /cidades
  # GET /cidades.json
  def index
    @cidades = Cidade.all
  end

  # GET /cidades/1
  # GET /cidades/1.json
  def show
  end

  # GET /cidades/new
  def new
    @cidade = Cidade.new
  end

  # GET /cidades/1/edit
  def edit
  end

  # POST /cidades
  # POST /cidades.json
  def create
    @cidade = Cidade.new(cidade_params)

    respond_to do |format|
      if @cidade.save
        format.html { redirect_to @cidade, notice: 'Cidade was successfully created.' }
        format.json { render :show, status: :created, location: @cidade }
      else
        format.html { render :new }
        format.json { render json: @cidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cidades/1
  # PATCH/PUT /cidades/1.json
  def update
    respond_to do |format|
      if @cidade.update(cidade_params)
        format.html { redirect_to @cidade, notice: 'Cidade was successfully updated.' }
        format.json { render :show, status: :ok, location: @cidade }
      else
        format.html { render :edit }
        format.json { render json: @cidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cidades/1
  # DELETE /cidades/1.json
  def destroy
    @cidade.destroy
    respond_to do |format|
      format.html { redirect_to cidades_url, notice: 'Cidade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cidade
      @cidade = Cidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cidade_params
      params.require(:cidade).permit(:nome, :qtd_habitantes, :area, :qtd_estacoes)
    end
end

app/helpers/cartaos_helper.rb
module CartaosHelper
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/estacaos_helper.rb
module EstacaosHelper
end

app/helpers/linhas_helper.rb
module LinhasHelper
end

app/helpers/metros_helper.rb
module MetrosHelper
end

app/helpers/onibuses_helper.rb
module OnibusesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cidades/_form.html.erb
<%= form_with(model: cidade, local: true) do |form| %>
  <% if cidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cidade.errors.count, "error") %> prohibited this cidade from being saved:</h2>

      <ul>
      <% cidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_area :nome, id: :cidade_nome %>
  </div>

  <div class="field">
    <%= form.label :qtd_habitantes %>
    <%= form.number_field :qtd_habitantes, id: :cidade_qtd_habitantes %>
  </div>

  <div class="field">
    <%= form.label :area %>
    <%= form.number_field :area, id: :cidade_area %>
  </div>

  <div class="field">
    <%= form.label :qtd_estacoes %>
    <%= form.number_field :qtd_estacoes, id: :cidade_qtd_estacoes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cidades/edit.html.erb
<h1>Editing Cidade</h1>

<%= render 'form', cidade: @cidade %>

<%= link_to 'Show', @cidade %> |
<%= link_to 'Back', cidades_path %>

app/views/cidades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cidades</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Qtd habitantes</th>
      <th>Area</th>
      <th>Qtd estacoes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cidades.each do |cidade| %>
      <tr>
        <td><%= cidade.nome %></td>
        <td><%= cidade.qtd_habitantes %></td>
        <td><%= cidade.area %></td>
        <td><%= cidade.qtd_estacoes %></td>
        <td><%= link_to 'Show', cidade %></td>
        <td><%= link_to 'Edit', edit_cidade_path(cidade) %></td>
        <td><%= link_to 'Destroy', cidade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cidade', new_cidade_path %>
<%= link_to 'Back', welcome_index_path %>

app/views/cidades/new.html.erb
<h1>New Cidade</h1>

<%= render 'form', cidade: @cidade %>

<%= link_to 'Back', cidades_path %>

app/views/cidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cidade.nome %>
</p>

<p>
  <strong>Qtd habitantes:</strong>
  <%= @cidade.qtd_habitantes %>
</p>

<p>
  <strong>Area:</strong>
  <%= @cidade.area %>
</p>

<p>
  <strong>Qtd estacoes:</strong>
  <%= @cidade.qtd_estacoes %>
</p>

<%= link_to 'Edit', edit_cidade_path(@cidade) %> |
<%= link_to 'Back', cidades_path %>